services:
  - type: web
    name: flask-ocr-app
    env: python
    plan: free
    buildCommand: |
      # Install Tesseract by downloading a pre-built binary
      apt-get update -o Acquire::http::Timeout=30 -o Acquire::ftp::Timeout=30 || true
      apt-get install -y wget
      wget https://github.com/tesseract-ocr/tesseract/releases/download/5.3.4/tesseract-ocr_5.3.4-1_amd64.deb
      dpkg -i tesseract-ocr_5.3.4-1_amd64.deb
      rm tesseract-ocr_5.3.4-1_amd64.deb
      # Install libtesseract-dev dependencies if needed
      apt-get install -y --fix-missing libtesseract-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app