services:
  - type: web
    name: flask-ocr-app
    env: python
    plan: free
    buildCommand: |
      for i in {1..3}; do apt-get update && apt-get install -y tesseract-ocr libtesseract-dev && break || sleep 5; done
      pip install -r requirements.txt
    startCommand: gunicorn app:app